name: List SSH Directory

on: 
  workflow_dispatch: 

jobs:
  check-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy SSH folder
        run: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa

      - name: Run your command
        run: ls -al ~/.ssh
